name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: "1.61.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Linux dependencies
        run: sudo apt-get install -y pkg-config build-essential libudev-dev
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1
      - run: cargo fmt -- --check
      - run: cargo clippy -- --deny=warnings
      - run: cargo build
      - run: cargo test

  build-nix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-12
          - macos-11
          - macos-10.15
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Setup Cachix
        uses: cachix/cachix-action@v11
        with:
          name: goki
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check -v --show-trace --no-update-lock-file
      - run: nix build --show-trace --print-build-logs
