name: Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: "1.57.0"

jobs:
  release-crate:
    runs-on: ubuntu-latest
    name: Release crate on crates.io
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - uses: Swatinem/rust-cache@v1
      - name: Publish crates
        run: cargo publish --token ${{ secrets.CARGO_PUBLISH_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
